### ISSUE TITLE
не грузится Quickpay-ссылка через .redirected_url()

### ISSUE THREAD

**Issue by Zakovskiy** [AlekseyKorshuk/yoomoney-api#10]
в последний месяц перестала работать форма платежа (была вечная загрузка и сумма не показывалась). как оказалось, просто `redirected_url()` почему-то начала выдавать невалидную ссылку, а через `base_url()` всё работает.

**Comment by AlekseyKorshuk** [comment]
Здравствуйте, еще актуально? Можете отправить код для репродукции этой ошибки?

**Comment by Zakovskiy** [comment]
уже нормально, вроде. но на всякий случай продолжу дальше base_url() использовать
