### ISSUE TITLE
the life cycle of the quickform

### ISSUE THREAD

**Issue by nayvok** [AlekseyKorshuk/yoomoney-api#11]
В статье на хабре Вы писали, что у второй ссылки есть жизненный цикл, я так понимаю время доступности формы оплаты. Хотел бы уточнить скольки она равна и можно ли установить свой таймер на форму оплаты?
Спасибо Вам за эту библиотеку)

**Comment by AlekseyKorshuk** [comment]
К сожалению, я не знаю ответа на ваш вопрос. Рекомендую обратить внимание на официальную документацию: https://yoomoney.ru/docs/wallet
