### ISSUE TITLE
Не работает получение токена

### ISSUE THREAD

**Issue by GODIMONGO** [AlekseyKorshuk/yoomoney-api#15]
Traceback (most recent call last):
  File "C:\Users\Дмитрий\PycharmProjects\pythonProject\test.py", line 3, in <module>
    Authorize(
  File "C:\Users\Дмитрий\PycharmProjects\pythonProject\.venv\Lib\site-packages\yoomoney\authorize\authorize.py", line 59, in __init__
    raise EmptyToken()
yoomoney.exceptions.EmptyToken: Response token is empty. Repeated request for an authorization token

Process finished with exit code 1

**Comment by GODIMONGO** [comment]
Я смог починить просто вмето сылки достанте токен

**Comment by GODIMONGO** [comment]
Если есть желание вы можете обратится ко мне в телеграм: @qsa95

**Comment by GODIMONGO** [comment]
> Подтверждаю, не работает

.

**Comment by GODIMONGO** [comment]
> @GODIMONGO можете создать pull request и обновить документацию по получению токена?

Что бы получить токен нужно использовать сылку без редиректов к примеру как у телеги на пк: https://t.me/GODIMONGO 
Далее в программу вставлять не всю сылку а именно токен после code=

**Comment by fenix120486** [comment]
> @GODIMONGOМожете ли вы создать запрос на включение и обновить документацию по полученному токену?

Я нашёл решение как убить этот вопрос, просто удалите сначало в настройках - безопасность - доступ к кошелеку ваш созданный shop, далее заново создайте и не ставьте галочку на против outh2

**Comment by AlekseyKorshuk** [comment]
[Resolved]

**Comment by GODIMONGO** [comment]
> > @GODIMONGOМожете ли вы создать запрос на включение и обновить документацию по полученному токену?
> 
> Я нашёл решение как убить этот вопрос, просто удалите сначало в настройках - безопасность - доступ к кошелеку ваш созданный shop, далее заново создайте и не ставьте галочку на против outh2 проверка безопасности.

Замечу это не единстенная проблема потому что многи сайты удаляют из сылок этот самый код для авторизации! А так же если в ответ как в инструкции прислать сылку а не сам код то у меня программа выдавала ошибку
