### ISSUE TITLE
Response token is empty. Repeated request for an authorization token

### ISSUE THREAD

**Issue by GagikProger** [AlekseyKorshuk/yoomoney-api#2]
Hi, how can I fix this exception?
yoomoney.exceptions.EmptyToken: Response token is empty. Repeated request for an authorization token

I have already another project where I did everything similar and token came. Now I need to change account so I authorize new application.

**Comment by AlekseyKorshuk** [comment]
Hello. 
Try to do the same manually: https://yoomoney.ru/docs/wallet/using-api/authorization/obtain-access-token
And if it works, then the problem would be on the repo side so ping me. 
Sorry for the long waiting 🤗

**Comment by GagikProger** [comment]
Ok, thank you for your answer. I will try

**Comment by GagikProger** [comment]
Hi. I did it manually and there was the same problem. The problem is not related to the account because I changed it too. So I think problem is on Yoomoney`s side

**Comment by johny322** [comment]
@progerg Привет. Столкнулся с такой же проблемой. Как тебе удалось ее решить?

**Comment by progerg** [comment]
> @progerg Привет. Столкнулся с такой же проблемой. Как тебе удалось ее решить?

Никак)
Пришлось перейти на киви

**Comment by johny322** [comment]
@progerg 
Жалко. Спасибо за ответ

**Comment by gresaggr** [comment]
Нужно добавить в запрос client_secret
`url = "https://yoomoney.ru/oauth/token?code={code}&client_id={client_id}&" \
              "grant_type=authorization_code&redirect_uri={redirect_uri}&client_secret={client_secret}".format(code=str(code),
                                                                                 client_id=client_id,
                                                                                 redirect_uri=redirect_uri,
                                                                                 client_secret=client_secret,
                                                                                 )`

Ждите пока автор добавит или вручную измените в authorize.py

**Comment by johny322** [comment]
Проблема была в самом аккаунте юмани. Был неполностью настроен, с ограничениями, из-за этого даже с client_secret не удавалось получить токен. Если кто-то столкнется с такой же проблемой, проверьте аккаунт

**Comment by innoky** [comment]
**Допилил код файла authorize.py, можете просто скопипастить, в самом запросе добавьте строку с client_secret и вставьте свой**
```
from typing import List
import requests

from yoomoney.exceptions import (
    InvalidRequest,
    UnauthorizedClient,
    InvalidGrant,
    EmptyToken
    )

class Authorize:
    def __init__(
            self,
            client_id: str,
            redirect_uri: str,
            client_secret: str,
            scope: List[str]
                  ):

        url = "https://yoomoney.ru/oauth/authorize?client_id={client_id}&response_type=code" \
              "&redirect_uri={redirect_uri}&scope={scope}".format(client_id=client_id,
                                                                  redirect_uri=redirect_uri,

                                                                  scope='%20'.join([str(elem) for elem in scope]),
                                                                  )

        headers = {
            'Content-Type': 'application/x-www-form-urlencoded'
        }

        response = requests.request("POST", url, headers=headers)

        if response.status_code == 200:
            print("Visit this website and confirm the application authorization request:")
            print(response.url)

        code = str(input("Enter redirected url (https://yourredirect_uri?code=XXXXXXXXXXXXX) or just code: "))
        try:
            code = code[code.index("code=") + 5:].replace(" ","")
        except:
            pass

        url = "https://yoomoney.ru/oauth/token?code={code}&client_id={client_id}&" \
              "grant_type=authorization_code&redirect_uri={redirect_uri}&client_secret={client_secret}".format(code=str(code), client_id=client_id, redirect_uri=redirect_uri, client_secret=client_secret )
        
        response = requests.request("POST", url, headers=headers)

        if "error" in response.json():
            error = response.json()["error"]
            if error == "invalid_request":
                raise InvalidRequest()
            elif error == "unauthorized_client":
                raise UnauthorizedClient()
            elif error == "invalid_grant":
                raise InvalidGrant()

        if response.json()['access_token'] == "":
            raise EmptyToken()

        print("Your access token:")
        print(response.json()['access_token'])
```

**Comment by SevaShpun** [comment]
@gresaggr @innoky, Спасибо ребят!
