### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by VReunov** [AlekseyKorshuk/yoomoney-api#5]
При запросе
`
token = "xxx"
client = Client(token)
history = client.operation_history(label="ххххх")`
 Получаю ошибку
`Traceback (most recent call last):
  File "/x/x/x/x.py", line 70, in ym_get
    history = client.operation_history()
  File "/usr/local/lib/python3.8/site-packages/yoomoney/client.py", line 44, in operation_history
    return History(base_url=self.base_url,
  File "/usr/local/lib/python3.8/site-packages/yoomoney/history/history.py", line 96, in __init__
    for operation_data in data["operations"]:
TypeError: string indices must be integers`

**Comment by AlekseyKorshuk** [comment]
@VReunov 
client.account_info() работает без ошибок?

**Comment by AlekseyKorshuk** [comment]
Для начала работы с YooMoney API нужно получить токен.
Следуй [инструкциям](https://github.com/AlekseyKorshuk/yoomoney-api#access-token) в README.

Я закрываю проблему. Если не получиться решить ее - открой проблему еще раз 🤗
