### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by chkyratov** [AlekseyKorshuk/yoomoney-api#6]
привет, такая проблема, когда запускаю твой код как в примере все работает, когда пытаюсь запихнуть тот же код в aiogram начинаются ошибки переполнения, не подскажешь как поправить?
еще вот такие ошибки:
RecursionError: maximum recursion depth exceeded
ERROR:asyncio:Task exception was never retrieved

**Comment by AlekseyKorshuk** [comment]
Можешь скинуть кусок кода у котором ошибка?
- сам вызов функции
- и функцию

**Comment by chkyratov** [comment]
вызов это коллбэк aiogram:

async def pay(callback: CallbackQuery, cat, subcat, t_id, full_name, **kwargs):
    await bill.user_info()

функия:

from data.config import TOKEN

class bill:

    async def user_info():
       client = Client(TOKEN)

       user = client.account_info()

       print("Account number:", user.account)
       print("Account balance:", user.balance)

отдельно эта функция работает отлично, из колбэка не вызывается.

**Comment by chkyratov** [comment]
все разобрался сам, проблема была в криворукости, спасибо за хороший код и быстрый ответ)
